export const GET_ALL_ZONES_REQUEST = "GET_ALL_ZONES_REQUEST";
export const GET_ALL_ZONES_SUCCESS = "GET_ALL_ZONES_SUCCESS";
export const GET_ALL_ZONES_FAILURE = "GET_ALL_ZONES_FAILURE";

export const CREATE_ZONE_REQUEST = "CREATE_ZONE_REQUEST";
export const CREATE_ZONE_SUCCESS = "CREATE_ZONE_SUCCESS";
export const CREATE_ZONE_FAILURE = "CREATE_ZONE_FAILURE";

export const UPDATE_ZONE_REQUEST = "UPDATE_ZONE_REQUEST";
export const UPDATE_ZONE_SUCCESS = "UPDATE_ZONE_SUCCESS";
export const UPDATE_ZONE_FAILURE = "UPDATE_ZONE_FAILURE";

export const DELETE_ZONE_REQEUST = "DELETE_ZONE_REQUEST";
export const DELETE_ZONE_SUCCESS = "DELETE_ZONE_SUCCESS";
export const DELETE_ZONE_FAILURE = "DELETE_ZONE_FAILURE";

export const CURRENT_ZONE_REQUEST = "CURRENT_ZONE_REQUEST";
export const CURRENT_ZONE_SUCCESS = "CURRENT_ZONE_SUCCESS";
export const CURRENT_ZONE_FAILURE = "CURRENT_ZONE_FAILURE";
