export const GET_SUMMARY_REQUEST = "GET_SUMMARY_REQUEST";
export const GET_SUMMARY_SUCCESS = "GET_SUMMARY_SUCCESS";
export const GET_SUMMARY_FAILURE = "GET_SUMMARY_FAILURE";

export const GET_RECENTSOS_REQEUST = "GET_RECENTSOS_REQEUST";
export const GET_RECENTSOS_SUCCESS = "GET_RECENTSOS_SUCCESS";
export const GET_RECENTSOS_FAILURE = "GET_RECENTSOS_FAILURE";

export const GET_STATS_REQUEST = "GET_STATS_REQUEST";
export const GET_STATS_SUCCESS = "GET_STATS_SUCCESS";
export const GET_STATS_FAILURE = "GET_STATS_FAILURE";
