export const GET_ALL_SOS_REQUEST = "GET_ALL_SOS_REQUEST";
export const GET_ALL_SOS_FAILURE = "GET_ALL_SOS_FAILURE";
export const GET_ALL_SOS_SUCCESS = "GET_ALL_SOS_SUCCESS";

export const CREATE_SOS_REQUEST = "CREATE_SOS_REQUEST";
export const CREATE_SOS_SUCCESS = "CREATE_SOS_SUCCESS";
export const CREATE_SOS_FAILURE = "CREATE_SOS_FAILURE";

export const GET_SOS_BY_ZONE_REQUEST = "GET_SOS_BY_ZONE_REQUEST";
export const GET_SOS_BY_ZONE_SUCCESS = "GET_SOS_BY_ZONE_SUCCESS";
export const GET_SOS_BY_ZONE_FAILURE = "GET_SOS_BY_ZONE_FAILURE";

export const UPDATE_STATUS_REQUEST = "UPDATE_STATUS_REQUEST";
export const UPDATE_STATUS_SUCCESS = "UPDATE_STATUS_SUCCESS";
export const UPDATE_STATUS_FAILURE = "UPDATE_STATUS_FAILURE";

export const MY_SOS_REQUEST = "MY_SOS_REQUEST";
export const MY_SOS_SUCCESS = "MY_SOS_SUCCESS";
export const MY_SOS_FAILURE = "MY_SOS_FAILURE";